
services :
  db:
    image: postgres:15
    container_name : postgres_db
    environment :
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : 12345678
      POSTGRES_DB : classify
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    container_name: backend
    ports: "8000:8000"
    environment: 
      DATABASE_URL: postgresql+psycopg2://postgres:12345678@localhost/classify
      HF_TOKEN: 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
    depends_on:
      - db
    volumes:
      - ./backend:/app
volumes:
  pgdata: